version: "3.8"
services:
  lct: 
    container_name: lct_cuda02
    image: lct_cuda01 
    # build:
      # context: .
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    # stop_signal: SIGINT
    ports:
      - '80:80'

# sudo docker run --gpus all --ipc=host -p 80:80 --name=lct_cuda04 lct_cuda04
